class ASTVisitor:
    def visitProgram(self, node): ...
    def visitReturn(self, node): ...
    def visitDecl(self, node): ...
    def visitAssign(self, node): ...
    def visitBinaryOp(self, node): ...
    def visitID(self, node): ...
    def visitNumber(self, node): ...
    def visitBool(self, node): ...
    def visitNot(self, node): ...
    def visitIf(self, node): ...
    def visitCodeBlock(self, node): ...
