
class ASTVisitor:
    def visitProgram(self, node): ...
    def visitReturn(self, node): ...
    def visitDecl(self, node): ...
    def visitAssign(self, node): ...
    def visitBinaryOp(self, node): ...
    def visitID(self, node): ...
    def visitNumber(self, node): ...
